random_state: 42
target_col: "target"
test_size: 0.2
cv_folds: 5

models:
  logistic_regression:
    C: 1.0
    penalty: "l2"
    class_weight: "balanced"
  random_forest:
    n_estimators: 300
    max_depth: null
    class_weight: "balanced"
  xgboost:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 6
  lightgbm:
    n_estimators: 400
    learning_rate: 0.05
    num_leaves: 31
